create table users
(
    username varchar_ignorecase(50)  not null primary key,
    password varchar_ignorecase(200) not null,
    enabled  boolean                 not null
);

create table authorities
(
    id        int primary key auto_increment,
    username  varchar_ignorecase(50) not null,
    authority varchar_ignorecase(50) not null
);
CREATE TABLE customer (id int, name varchar(50), phone varchar(50));
create table country (
                         id bigint generated by default as identity, -- it should be country code
                         name varchar(255),
                         phone_regex varchar(255),
                         primary key (id)
)